#!/bin/sh

# Environment variables
export PATH="${PATH}:~/scripts"
export WALLPAPER_DIR="$HOME/wallpapers"
#export WALLPAPER="$WALLPAPER_DIR/arch_layers.png"

files=($WALLPAPER_DIR/*)
export WALLPAPER=`printf "%s\n" "${files[RANDOM % ${#files[@]}]}"`

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec awesome
