require('dixiedream/pluginDisabler')
require('dixiedream/lightline')
require('dixiedream/cmp')
require('dixiedream/comments')
require('dixiedream/lspconfig')
require('dixiedream/treesitter')
require('dixiedream/telescope')
