require('dixiedream/pluginDisabler')
require('dixiedream/statusbar')
require('dixiedream/cmp')
require('dixiedream/comments')
require('dixiedream/harpoon')
require('dixiedream/lspconfig')
require('dixiedream/treesitter')
require('dixiedream/telescope')
