#!/bin/bash

IMG_PATH="$HOME/screenshots/"
TIME=3000 #Miliseconds notification should remain visible


prog="1.quick_fullscreen
2.delayed_fullscreen
3.section"

#cmd=$(dmenu  -l 20  -nf '#999' -nb '#292d3e' -sf '#eee' -sb '#0077bb' -p 'Choose Screenshot Type'   <<< "$prog")

cmd=$(dmenu -p 'Choose Screenshot Type' <<< "$prog")

cd $IMG_PATH
case ${cmd%% *} in
	1.quick_fullscreen)	scrot -d 1 '%Y-%m-%d-@%H-%M-%S-scrot.png'  && notify-send -u low -t $TIME 'Scrot' 'Fullscreen taken and saved'  ;;
	2.delayed_fullscreen)	scrot -d 4 '%Y-%m-%d-@%H-%M-%S-scrot.png'  && notify-send -u low -t $TIME 'Scrot' 'Fullscreen Screenshot saved'    ;;
	3.section)	scrot -s '%Y-%m-%d-@%H-%M-%S-scrot.png' && notify-send -u low -t $TIME 'Scrot' 'Screenshot of section saved'    ;;
  	*)		exec "'${cmd}'"  ;;
esac

